language: node_js
node_js:
  - 11
cache: npm

addons:
  ssh_known_hosts: kethoughts.com

branches:
  only:
  - master

before_install:
  - git clone $TRAVIS_ENC_REPO
  - openssl aes-256-cbc -K $encrypted_7e02c3319e2b_key -iv $encrypted_7e02c3319e2b_iv
    -in travis_encrypt/kethoughts_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
  - cd './web'

install:
  - npm install

script:
  - npm run build

after_script:
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/travis_rsa
  - cd ../dist
  - git init
  - git config user.name "travis"
  - git config user.email "travis@travis-ci.com"
  - git add .
  - git commit -m "deployment"
  - git remote add deploy "${WEB_SERVER}:${WEB_FOLDER}"
  - git push --force deploy HEAD:master

notifications:
  email: false