
---
appName: kethoughts.com

server:
  port: 5000
  secret: jwt_auth_secret_key

mysql:
  host: 127.0.0.1
  port: 3306
  database: kethoughts_db
  user: kethoughts_user
  password: kethoughts_pass

weixin:
  appId: your_weixin_appid
  appSecret: your_weixin_appsecret
  token: weixin

qiniu:
  accesskey: your_qiniu_accesskey
  secretkey: your_qiniu_secretkey